# Generated by Django 5.0.2 on 2024-08-30 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_categoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccaoDepartamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('estado_objecto', models.CharField(choices=[('activo', 'Activo'), ('eliminado', 'Eliminado')], default='activo', max_length=200, verbose_name='estado objecto')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('estado_objecto', models.CharField(choices=[('activo', 'Activo'), ('eliminado', 'Eliminado')], default='activo', max_length=200, verbose_name='estado objecto')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
