# Generated by Django 5.0.2 on 2024-08-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_funcao_chefia_nova_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccaoDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Estacao')),
            ],
        ),
    ]
