# Generated by Django 5.0.2 on 2024-08-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_direccaodepartamento_estacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DireccaoDepartamento',
        ),
        migrations.DeleteModel(
            name='Estacao',
        ),
    ]
