# Generated by Django 5.0.2 on 2024-08-30 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0003_direccaodepartamento_estacao'),
        ('employees', '0013_delete_direccaodepartamento_delete_estacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='direccaoDepart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.direccaodepartamento', verbose_name='Departamento ou Direcção'),
        ),
        migrations.AddField(
            model_name='employee',
            name='estacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.estacao', verbose_name='Estacão'),
        ),
    ]
